import { Router } from "express";
import { PersonalInfoRouter } from "./PersonalInfo.router";
import { UserRouter } from "./User.router";
import { AddressRouter } from "./Address.router";
import { AddresExtraInfoRouter } from "./AddressExtraInfo.router";
import { GovermentInfoRouter } from "./GovermentInfo.router";
import { ProfileRouter } from "./Profile.router"; 
import { AcademicInfoRouter } from "./AcademicInfo.router";
import { FormalEducationInfoRouter } from "./FormalEducationInfo.router";
import { ScholarshipInfoRouter } from "./ScholarshipInfo.router";
import { BankAccountInfoRouter } from "./BankAccountInfo.router";
import { SkillsRouter } from "./Skills.router";
const APIRouter = Router();
APIRouter.use("/personalInfo", PersonalInfoRouter);
APIRouter.use("/user", UserRouter);
APIRouter.use("/address", AddressRouter);
APIRouter.use("/addressExtraInfo", AddresExtraInfoRouter);
APIRouter.use("/govermentInfo", GovermentInfoRouter);
APIRouter.use("/profile", ProfileRouter);
APIRouter.use("/academicInfo", AcademicInfoRouter);
APIRouter.use("/formalEducationInfo", FormalEducationInfoRouter);
APIRouter.use("/scholarshipInfo", ScholarshipInfoRouter);
APIRouter.use("/bankAccount", BankAccountInfoRouter);
APIRouter.use("/skillsInfo", SkillsRouter);
export default APIRouter;
